
-- GUARDIAN 테이블 데이터 (보호자 5명)
CREATE TABLE GUARDIAN (
    GUARDIAN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255),
    DETAILED_ADDRESS VARCHAR(255),
    POSTAL_CODE VARCHAR(10),
    TEL VARCHAR(20),
    PHONE VARCHAR(20) ,
    ROLE VARCHAR(50) NOT NULL,
    GUARDIAN_STATUS VARCHAR(50) NOT NULL
);
-- GUARDIAN 데이터 삽입
INSERT INTO GUARDIAN (GUARDIAN_ID, EMAIL, PASSWORD, NAME, ADDRESS, DETAILED_ADDRESS, POSTAL_CODE, TEL, PHONE, ROLE, GUARDIAN_STATUS)
VALUES (1, 'guardian1@example.com', '$2a$10$n7p4K3MiMB9Jh5zRaRkdtOdkl5NNCs8ZDT6gP6KIANtYX/yj.8a3i', '김보호자', '서울 강남구', 'A동 101호', '06234', '02-1234-5678', '010-1111-2222', 'GUARDIAN', 'GUARDIAN_ACTIVE');

INSERT INTO GUARDIAN (GUARDIAN_ID, EMAIL, PASSWORD, NAME, ADDRESS, DETAILED_ADDRESS, POSTAL_CODE, TEL, PHONE, ROLE, GUARDIAN_STATUS)
VALUES (2, 'guardian2@example.com', '$2a$10$n7p4K3MiMB9Jh5zRaRkdtOdkl5NNCs8ZDT6gP6KIANtYX/yj.8a3i', '박보호자', '서울 서초구', 'B동 202호', '06543', '02-2345-6789', '010-2222-3333', 'GUARDIAN', 'GUARDIAN_ACTIVE');

INSERT INTO GUARDIAN (GUARDIAN_ID, EMAIL, PASSWORD, NAME, ADDRESS, DETAILED_ADDRESS, POSTAL_CODE, TEL, PHONE, ROLE, GUARDIAN_STATUS)
VALUES (3, 'guardian3@example.com', '$2a$10$n7p4K3MiMB9Jh5zRaRkdtOdkl5NNCs8ZDT6gP6KIANtYX/yj.8a3i', '이보호자', '서울 송파구', 'C동 303호', '13894', '02-3456-7890', '010-3333-4444', 'GUARDIAN', 'GUARDIAN_ACTIVE');

INSERT INTO GUARDIAN (GUARDIAN_ID, EMAIL, PASSWORD, NAME, ADDRESS, DETAILED_ADDRESS, POSTAL_CODE, TEL, PHONE, ROLE, GUARDIAN_STATUS)
VALUES (4, 'guardian4@example.com', '$2a$10$n7p4K3MiMB9Jh5zRaRkdtOdkl5NNCs8ZDT6gP6KIANtYX/yj.8a3i', '최보호자', '서울 광진구', 'D동 404호', '04994', '02-4567-8901', '010-4444-5555', 'GUARDIAN', 'GUARDIAN_ACTIVE');

INSERT INTO GUARDIAN (GUARDIAN_ID, EMAIL, PASSWORD, NAME, ADDRESS, DETAILED_ADDRESS, POSTAL_CODE, TEL, PHONE, ROLE, GUARDIAN_STATUS)
VALUES (5, 'guardian5@example.com', '$2a$10$n7p4K3MiMB9Jh5zRaRkdtOdkl5NNCs8ZDT6gP6KIANtYX/yj.8a3i', '정보호자', '서울 마포구', 'E동 505호', '04084', '02-5678-9012', '010-5555-6666', 'GUARDIAN', 'GUARDIAN_ACTIVE');

-- ADMIN 테이블 생성
CREATE TABLE IF NOT EXISTS ADMIN (
    ADMIN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ADMIN_CODE VARCHAR(50) NOT NULL UNIQUE,
    ADMIN_STATUS VARCHAR(50) NOT NULL,
    LOCATION VARCHAR(100),
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50)
);

-- ADMIN 데이터 추가
INSERT INTO ADMIN (ADMIN_ID, ADMIN_CODE, ADMIN_STATUS, LOCATION, PASSWORD,  ROLE)
VALUES
(1, 'ADMIN001', 'ADMIN_ACTIVE', '서울 강남구청', '$2a$10$n7p4K3MiMB9Jh5zRaRkdtOdkl5NNCs8ZDT6gP6KIANtYX/yj.8a3i',  'ADMIN');
INSERT INTO ADMIN (ADMIN_ID, ADMIN_CODE, ADMIN_STATUS, LOCATION, PASSWORD, ROLE)
VALUES
(2, 'ADMIN002', 'ADMIN_ACTIVE', '서울 서초구청', '$2a$10$n7p4K3MiMB9Jh5zRaRkdtOdkl5NNCs8ZDT6gP6KIANtYX/yj.8a3i',  'ADMIN');
INSERT INTO ADMIN (ADMIN_ID, ADMIN_CODE, ADMIN_STATUS, LOCATION, PASSWORD,  ROLE)
VALUES
(3, 'ADMIN003', 'ADMIN_ACTIVE', '서울 송파구청', '$2a$10$n7p4K3MiMB9Jh5zRaRkdtOdkl5NNCs8ZDT6gP6KIANtYX/yj.8a3i',  'ADMIN');
INSERT INTO ADMIN (ADMIN_ID, ADMIN_CODE, ADMIN_STATUS, LOCATION, PASSWORD,  ROLE)
VALUES
(4, 'ADMIN004', 'ADMIN_ACTIVE', '서울 광진구청', '$2a$10$n7p4K3MiMB9Jh5zRaRkdtOdkl5NNCs8ZDT6gP6KIANtYX/yj.8a3i', 'ADMIN');
INSERT INTO ADMIN (ADMIN_ID, ADMIN_CODE, ADMIN_STATUS, LOCATION, PASSWORD,  ROLE)
VALUES
(5, 'ADMIN005', 'ADMIN_ACTIVE', '서울 마포구청', '$2a$10$n7p4K3MiMB9Jh5zRaRkdtOdkl5NNCs8ZDT6gP6KIANtYX/yj.8a3i',  'ADMIN');


-- MEMBER 테이블 데이터 (사용자 5명)
CREATE TABLE MEMBER (
    MEMBER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ADDRESS VARCHAR(255),
    ADMIN_NOTE VARCHAR(255),
    AGE INT,
    BIRTH_DATE DATE,
    DETAILED_ADDRESS VARCHAR(255),
    DOCUMENT_ATTACHMENT VARCHAR(255),
    EMERGENCY_CONTACT VARCHAR(255),
    MEDICAL_HISTORY VARCHAR(255),
    MEMBER_CODE VARCHAR(50) UNIQUE,
    MEMBER_STATUS VARCHAR(50),
    MILK_DELIVERY_REQUEST VARCHAR(3),
    NAME VARCHAR(100),
    NOTES VARCHAR(255),
    PHONE VARCHAR(20),
    PHONE_INACTIVE_DURATION INT,
    POSTAL_CODE VARCHAR(10),
    POWER_USAGE INT,
    RELATIONSHIP VARCHAR(50),
    RESIDENT_NUMBER VARCHAR(50),
    ROLE VARCHAR(50),
    TEL VARCHAR(20),
    GUARDIAN_ID BIGINT
);

-- GUARDIAN 테이블 데이터 (보호자 5명)
CREATE TABLE GUARDIAN (
    GUARDIAN_ID BIGINT PRIMARY KEY,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255),
    DETAILED_ADDRESS VARCHAR(255),
    POSTAL_CODE VARCHAR(10),
    TEL VARCHAR(20),
    PHONE VARCHAR(20) UNIQUE,
    ROLE VARCHAR(50) NOT NULL,
    GUARDIAN_STATUS VARCHAR(50) NOT NULL
);

